# Autogenerated by devscripts/update-version.py

__version__ = '2025.02.19.112056'

RELEASE_GIT_HEAD = '8469b5c69cbba8a6648ba20295ef28da17947954'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'thanhtaivtt/yt-dlp'

ORIGIN = 'thanhtaivtt/yt-dlp'

_pkg_version = '2025.02.19.112056'
