# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.03.143214'

RELEASE_GIT_HEAD = '5bce979da95c9293c88965a02e0ce391623b674e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'thanhtaivtt/yt-dlp'

ORIGIN = 'thanhtaivtt/yt-dlp'

_pkg_version = '2026.02.03.143214'
