# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.25.141207'

RELEASE_GIT_HEAD = '10617f9f244afce36f0a836f82b3f99db1285809'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'thanhtaivtt/yt-dlp'

ORIGIN = 'thanhtaivtt/yt-dlp'

_pkg_version = '2025.03.25.141207'
